### ISSUE TITLE
ios webkit debug proxy disconnects from safari on  ios 8.1 physical device with error

### ISSUE THREAD

**Issue by vamsys** [google/ios-webkit-debug-proxy#79]
Running selenium tests on an ipad with ios 8.1

config as below:

ios 8.1
appium 1.2.3
ios webkit debug proxy 1.4
xcode 6,1

safari launcher is launched successfully, browsers open and then ios_webkit_debug_proxy disconnects from browser with error as below:
#################################################################################
Invalid message _rpc_applicationUpdated: <dict>
	<key>WIRApplicationIdentifierKey</key>
	<string>PID:459</string>
	<key>WIRIsApplicationProxyKey</key>
	<true/>
	<key>WIRApplicationNameKey</key>
	<string></string>
	<key>WIRApplicationBundleIdentifierKey</key>
	<string>com.apple.WebKit.WebContent</string>
	<key>WIRIsApplicationActiveKey</key>
	<integer>0</integer>
	<key>WIRHostApplicationIdentifierKey</key>
	<string>PID:457</string>
</dict>
ss.remove_fd(10)
Disconnected :27753 from Pacific’s iPad
#################################################################################
APPIUM LOGS:
##############################################################################
rror: [REMOTE] Could not connect to WebKitRemoteDebugger server
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Could not navigate to webview! Err: Error: connect ECONNREFUSED
info: [debug] Error: Could not navigate to webview! Err: Error: connect ECONNREFUSED
    at null.<anonymous> (/www/appium-1.0.0/appium/lib/devices/ios/ios.js:1517:12)
    at null.<anonymous> (/www/appium-1.0.0/appium/lib/devices/ios/ios-controller.js:1510:14)
    at null.<anonymous> (/www/appium-1.0.0/appium/lib/devices/ios/webkit-remote-debugger.js:73:14)
    at ClientRequest.<anonymous> (/www/appium-1.0.0/appium/node_modules/underscore/underscore.js:754:19)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:440:14
    at process._tickDomainCallback (node.js:459:13)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not navigate to webview! Err: Error: connect ECONNREFUSED)","origValue":"Could not navigate to webview! Err: Error: connect ECONNREFUSED"},"sessionId":null}
info: <-- POST /wd/hub/session 500 16300.643 ms - 248

**Comment by snevesbarros** [comment]
@jchuong I believe this can be solved by changing the proxy to just forward the Web Inspector messages it receives rather than trying to translate from webkit protocol and web-inspector protocol.

E.g. just have it accept web inspector messages and forward them to the device and vice versa. We specifically changed appium to use the webkit protocol, but should be able to reverse that if the proxy accepts web inspector protocol. That should prevent any issues in the future around incompatible messages.

How difficult would it be to strip the "translation" out of the proxy?

Or am i just talking crazy here ;)

**Comment by jchuong** [comment]
@snevesbarros I am using my changes for basic mobile Safari testing and it holds up pretty well.  Since I'm not doing any other mobile apps I can't tell if that is an issue or not.

As for forwarding messages, while I don't really know the inner workings of i-w-d-p, then it would probably be better to change Appium to connect to [usbmuxd](https://github.com/libimobiledevice/usbmuxd) rather than changing i-w-d-p.

**Comment by cades** [comment]
same problem +1

**Comment by jchuong** [comment]
@cades Please try my fork and see if it solves your problem, seems to work for snevebarros now
https://github.com/jchuong/ios-webkit-debug-proxy

**Comment by Joyge** [comment]
@jchuong Could you please provide information on how to build and install your forked branch on MacBook? I have downloaded the zip file from https://github.com/jchuong/ios-webkit-debug-proxy. But when I run "brew install ios-webkit-debug-proxy", it seems to download again from another site.

**Comment by jchuong** [comment]
@Joyge I'm not sure if you got the 1.4 zip or if it contains the source code but brew the dependencies:
libplist
libusbmuxd
libimobiledevice

You might need autoconf and automake too.

Clone the repository:  `git clone https://github.com/jchuong/ios-webkit-debug-proxy.git`
and go into the the new directory created. 
````
  ./autogen.sh
  ./configure
  make
  sudo make install
````

**Comment by tarunsujit** [comment]
@jchuong I got the Error when cloned and ran the command you provided in above comment. Please see complete logs



Sujits-MacBook-Pro:GitHub sujittarun$ git clone https://github.com/jchuong/ios-webkit-debug-proxy.git
Cloning into 'ios-webkit-debug-proxy'...
remote: Counting objects: 341, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 341 (delta 22), reused 15 (delta 11)
Receiving objects: 100% (341/341), 448.42 KiB | 117.00 KiB/s, done.
Resolving deltas: 100% (205/205), done.
Checking connectivity... done.
Sujits-MacBook-Pro:GitHub sujittarun$ ls
SafariLauncher		appium1.2.4		sample-code
appium			ios-webkit-debug-proxy
Sujits-MacBook-Pro:GitHub sujittarun$ cd ios-webkit-debug-proxy/
Sujits-MacBook-Pro:ios-webkit-debug-proxy sujittarun$ ./autogen.sh
aclocal
autoheader
automake --add-missing
configure.ac:13: installing './compile'
configure.ac:8: installing './install-sh'
configure.ac:8: installing './missing'
examples/Makefile.am: installing './depcomp'
autoconf
Sujits-MacBook-Pro:ios-webkit-debug-proxy sujittarun$   ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for idevice_connect in -limobiledevice... no
checking for plist_to_xml in -lplist... no
checking for log10 in -lm... yes
checking for sys/types.h... yes
checking for netinet/in.h... yes
checking for arpa/nameser.h... yes
checking for netdb.h... yes
checking for resolv.h... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... (cached) yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking for inttypes.h... (cached) yes
checking for netdb.h... (cached) yes
checking for netinet/in.h... (cached) yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for int8_t... yes
checking for size_t... yes
checking for ssize_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for memmove... yes
checking for memset... yes
checking for regcomp... yes
checking for select... yes
checking for socket... yes
checking for stpcpy... yes
checking for strcasecmp... yes
checking for strncasecmp... yes
checking for strchr... yes
checking for strdup... yes
checking for strndup... yes
checking for strrchr... yes
checking for strstr... yes
checking for strtol... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating include/Makefile
config.status: creating examples/Makefile
config.status: creating config.h
config.status: executing depfiles commands
Sujits-MacBook-Pro:ios-webkit-debug-proxy sujittarun$   make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
gcc -DHAVE_CONFIG_H -I. -I..  -I../include     -g -O2 -Wall -Werror -MT ios_webkit_debug_proxy_main.o -MD -MP -MF .deps/ios_webkit_debug_proxy_main.Tpo -c -o ios_webkit_debug_proxy_main.o ios_webkit_debug_proxy_main.c
In file included from ios_webkit_debug_proxy_main.c:23:
../include/webinspector.h:15:10: fatal error: 'plist/plist.h' file not found
#include <plist/plist.h>
         ^
1 error generated.
make[2]: *** [ios_webkit_debug_proxy_main.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Sujits-MacBook-Pro:ios-webkit-debug-proxy sujittarun$   sudo make install
Password:
Making install in src
gcc -DHAVE_CONFIG_H -I. -I..  -I../include     -g -O2 -Wall -Werror -MT ios_webkit_debug_proxy_main.o -MD -MP -MF .deps/ios_webkit_debug_proxy_main.Tpo -c -o ios_webkit_debug_proxy_main.o ios_webkit_debug_proxy_main.c
In file included from ios_webkit_debug_proxy_main.c:23:
../include/webinspector.h:15:10: fatal error: 'plist/plist.h' file not found
#include <plist/plist.h>
         ^
1 error generated.
make[1]: *** [ios_webkit_debug_proxy_main.o] Error 1
make: *** [install-recursive] Error 1

**Comment by tarunsujit** [comment]
@jchuong I got this error message.

Sujits-MacBook-Pro:ios-webkit-debug-proxy sujittarun$ brew install automake
Warning: automake-1.15 already installed
Sujits-MacBook-Pro:ios-webkit-debug-proxy sujittarun$ brew install autoconf
Warning: autoconf-2.69 already installed
Sujits-MacBook-Pro:ios-webkit-debug-proxy sujittarun$ sudo make install
Password:
Making install in src
gcc -DHAVE_CONFIG_H -I. -I..  -I../include     -g -O2 -Wall -Werror -MT ios_webkit_debug_proxy_main.o -MD -MP -MF .deps/ios_webkit_debug_proxy_main.Tpo -c -o ios_webkit_debug_proxy_main.o ios_webkit_debug_proxy_main.c
In file included from ios_webkit_debug_proxy_main.c:23:
../include/webinspector.h:15:10: fatal error: 'plist/plist.h' file not found
#include <plist/plist.h>
         ^
1 error generated.
make[1]: *** [ios_webkit_debug_proxy_main.o] Error 1
make: *** [install-recursive] Error 1

**Comment by jchuong** [comment]
@tarunsujit It looks like you didn't brew the dependencies:

````
brew install libplist
brew install libusbmuxd
brew install libimobiledevice
````

I guess I will update the README later to explicitly show installation steps.

**Comment by tarunsujit** [comment]
I having these @jchuong 


Sujits-MacBook-Pro:~ sujittarun$ brew install libplist
Warning: libplist-1.12 already installed
Sujits-MacBook-Pro:~ sujittarun$ brew install libusbmuxd
Error: No available formula for libusbmuxd 
Searching formulae...
Searching taps...
Sujits-MacBook-Pro:~ sujittarun$ brew install libimobiledevice
Warning: libimobiledevice-HEAD already installed

**Comment by jchuong** [comment]
@tarunsujit If libplist is installed, you should have the include file in `/usr/local/Cellar/libplist/1.12/include/plist/plist.h`...

I'm curious why `sudo make install` is compiling the code, when it should only just copy the binaries.

**Comment by tarunsujit** [comment]
I see file present in the path

Sujits-MacBook-Pro:~ sujittarun$ cd /usr/local/Cellar/libplist/1.12/include/plist
Sujits-MacBook-Pro:plist sujittarun$ ls
Array.h		Date.h		Key.h		String.h	plist++.h
Boolean.h	Dictionary.h	Node.h		Structure.h	plist.h
Data.h		Integer.h	Real.h		Uid.h

I am not sure why it is compiling, Can I manually copy the file somewhere? what can i do here?

**Comment by jchuong** [comment]
I think you *could* copy the include but that shouldn't be the solution (because if this happens to plist, this will probably happen with the other libraries).

I noticed that you didn't seem to have done
````
  ./autogen.sh
  ./configure
  make
  sudo make install
````
Can you confirm that you did do all 4 commands in the ios-webkit-debug-proxy folder?

**Comment by tarunsujit** [comment]
I did it. But re-ran these commands again. Please see below logs..


Sujits-MacBook-Pro:ios-webkit-debug-proxy sujittarun$ ./autogen.sh
aclocal
autoheader
automake --add-missing
autoconf
Sujits-MacBook-Pro:ios-webkit-debug-proxy sujittarun$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for idevice_connect in -limobiledevice... no
checking for plist_to_xml in -lplist... no
checking for log10 in -lm... yes
checking for sys/types.h... yes
checking for netinet/in.h... yes
checking for arpa/nameser.h... yes
checking for netdb.h... yes
checking for resolv.h... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... (cached) yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking for inttypes.h... (cached) yes
checking for netdb.h... (cached) yes
checking for netinet/in.h... (cached) yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for int8_t... yes
checking for size_t... yes
checking for ssize_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for memmove... yes
checking for memset... yes
checking for regcomp... yes
checking for select... yes
checking for socket... yes
checking for stpcpy... yes
checking for strcasecmp... yes
checking for strncasecmp... yes
checking for strchr... yes
checking for strdup... yes
checking for strndup... yes
checking for strrchr... yes
checking for strstr... yes
checking for strtol... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating include/Makefile
config.status: creating examples/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
Sujits-MacBook-Pro:ios-webkit-debug-proxy sujittarun$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
gcc -DHAVE_CONFIG_H -I. -I..  -I../include     -g -O2 -Wall -Werror -MT ios_webkit_debug_proxy_main.o -MD -MP -MF .deps/ios_webkit_debug_proxy_main.Tpo -c -o ios_webkit_debug_proxy_main.o ios_webkit_debug_proxy_main.c
In file included from ios_webkit_debug_proxy_main.c:23:
../include/webinspector.h:15:10: fatal error: 'plist/plist.h' file not found
#include <plist/plist.h>
         ^
1 error generated.
make[2]: *** [ios_webkit_debug_proxy_main.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Sujits-MacBook-Pro:ios-webkit-debug-proxy sujittarun$ sudo make install
Password:
Making install in src
gcc -DHAVE_CONFIG_H -I. -I..  -I../include     -g -O2 -Wall -Werror -MT ios_webkit_debug_proxy_main.o -MD -MP -MF .deps/ios_webkit_debug_proxy_main.Tpo -c -o ios_webkit_debug_proxy_main.o ios_webkit_debug_proxy_main.c
In file included from ios_webkit_debug_proxy_main.c:23:
../include/webinspector.h:15:10: fatal error: 'plist/plist.h' file not found
#include <plist/plist.h>
         ^
1 error generated.
make[1]: *** [ios_webkit_debug_proxy_main.o] Error 1
make: *** [install-recursive] Error 1

**Comment by tarunsujit** [comment]
I see people face the same exact problem : https://github.com/google/ios-webkit-debug-proxy/issues/76

**Comment by jchuong** [comment]
These two lines:

````
checking for idevice_connect in -limobiledevice... no
checking for plist_to_xml in -lplist... no
````

Should be yes, so it means something is wrong with your installation of the libraries (libmobiledevice, libplist).

I'm on
libplist 1.12
libimobiledevice 1.1.7
usbmuxd 1.0.10

**Comment by tarunsujit** [comment]
Mee too, i have same exact versions

Sujits-MacBook-Pro:ios-webkit-debug-proxy sujittarun$ brew install libplist
Warning: libplist-1.12 already installed
Sujits-MacBook-Pro:ios-webkit-debug-proxy sujittarun$ brew install libimobiledevice
Warning: libimobiledevice-HEAD already installed
Sujits-MacBook-Pro:ios-webkit-debug-proxy sujittarun$ brew install usbmuxd
Warning: usbmuxd-1.0.10 already installed

**Comment by jchuong** [comment]
Actually, check that the plist/plist.h file exists in /usr/local/include. I'm not exactly sure what I did to have the includes installed there but you might have to fiddle with homebrew.  Try updating brew, brew doctor and reinstalling the libraries.

**Comment by Afforess** [comment]
I had the same issue and I can confirmed jchuong's repo fixes the issues and allows me to debug iOS 8.1.2 correctly.

**Comment by tarunsujit** [comment]
@jchuong I tried all possible ways, but no luck.
I removed brew and installed it again.. but still the same issue. Please suggest

**Comment by jchuong** [comment]
@tarunsujit Sorry I don't know how to fix your issue.  The only way I can reproduce this is by uninstalling the libraries, but that is solved by brew install again.   Try to `brew unlink libplist` and then `brew link libplist`, you should check that /usr/local/include/plist was removed, then created.  If not, then there is an issue with how brew is linking a directory.

**Comment by cosminduracsv** [comment]
@jchuong  - I used the fix added in https://github.com/jchuong/ios-webkit-debug-proxy and it resolves the problem related to ios-webkit-debug-proxy being disconected. Now the ios-webkit-debug-proxy remains connected all the time, but still appium says:
error: [REMOTE] Could not connect to WebKitRemoteDebugger server
error: Failed to start an Appium session, err was: Error: Could not navigate to webview! Err: Error: connect ECONNREFUSED
Any idea why?

**Comment by jchuong** [comment]
@cosminduracsv Sorry, with just that I can't tell what is wrong.  If you can show me if there is a message in iwdp or some more information then maybe.

**Comment by cosminduracsv** [comment]
@jchuong Here is what i get in iwdp:
Unknown app_id PID:215
Invalid message _rpc_applicationSentListing: <dict>
 <key>WIRApplicationIdentifierKey</key>
 <string>PID:215</string>
 <key>WIRListingKey</key>
 <dict>
  <key>1</key>
  <dict>
   <key>WIRTitleKey</key>
   <string>Granular</string>
   <key>WIRTypeKey</key>
   <string>WIRTypeWeb</string>
   <key>WIRURLKey</key>
   <string>http://local.granular.ag:6543/</string>
   <key>WIRPageIdentifierKey</key>
   <integer>1</integer>
  </dict>
 </dict>
</dict>

**Comment by snevesbarros** [comment]
@cosminduracsv, I believe this also happens when there is still an existing connection to the proxy. Please check you are: 
1. Always using webdriver.quit() to close the previous connection properly
2. Don't have chrome open with page http://127.0.0.1:27753 opened (as that takes up the connection as well)

**Comment by tauheedkhan** [comment]
hey, make command giving error:
websocket.c:327:7: error: expression result unused [-Werror,-Wunused-value]
      *out_tail++;

**Comment by jchuong** [comment]
https://github.com/google/ios-webkit-debug-proxy/issues/104

PR is already ready but I haven't gotten any confirmation that everything is okay,

**Comment by tauheedkhan** [comment]
I checked, fix is working fine

**Comment by artygus** [comment]
@jchuong it's pretty easy to check, most of the websocket requests would stop to work. I have doubts regarding the 'implicit declaration of function 'htons' [-Werror=implicit-function-declaration]' error, but OP of #103 haven't responded to the PR yet

**Comment by jchuong** [comment]
@tauheedkhan @artygus Thanks, I just don't have a real device with me so I don't want to say its actually working.  I will also close this issue because I believe it is fixed for 8.1.. I think some people changes for 8.2,8.3 instead now.

**Comment by Swapnillll** [comment]
@jchuong i tried this fix in 8.4. It works, proxy is not disconnecting now. But i saw another issue like my test url is not launched in the browser after this update.

Worked fine when i started the proxy from the ios-webkit js file before taking this fix.

**Comment by Sendami** [comment]
For me keeps without working in 8.1.3 with ipad air
