### ISSUE TITLE
Build failure with recent gcc

### ISSUE THREAD

**Issue by micwoj92** [google/ios-webkit-debug-proxy#432]
Hello,

Version 1.9.2 fails to build with `gcc version 15.2.1 20260209 (GCC)` with following error:
```
ios_webkit_debug_proxy.c: In function ‘iwdp_get_content_type’:
ios_webkit_debug_proxy.c:1974:18: error: initialization discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
 1974 |     char *fext = strrchr(path, '.');
      |                  ^~~~~~~
```

**Comment by micwoj92** [comment]
Seems like this is due to change mentioned in glibc 2.43 release notes:
```
For ISO C23, the functions bsearch, memchr, strchr, strpbrk, strrchr,
  strstr, wcschr, wcspbrk, wcsrchr, wcsstr and wmemchr that return
  pointers into their input arrays now have definitions as macros that
  return a pointer to a const-qualified type when the input argument is
  a pointer to a const-qualified type.
```
```
* The aforementioned change in ISO C23 of the declaration of bsearch,
  memchr, strchr, strpbrk, strrchr, strstr, wcschr, wcspbrk, wcsrchr,
  wcsstr, and wmemchr as const-preserving macros can lead to compilation
  issues in code not set up for it. In particular, gnulib snapshots may need
  to be updated.
```

**Comment by binarykitchen** [comment]
Yes, I experience the same error upon `make` on my Arch Linux machine:

```bash
make  all-recursive
make[1]: Entering directory '/home/michael-heuberger/code/binarykitchen/ios-webkit-debug-proxy'
Making all in src
make[2]: Entering directory '/home/michael-heuberger/code/binarykitchen/ios-webkit-debug-proxy/src'
gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I../include/ios-webkit-debug-proxy        -g -O2 -Wall -Werror -MT ios_webkit_debug_proxy-ios_webkit_debug_proxy.o -MD -MP -MF .deps/ios_webkit_debug_proxy-ios_webkit_debug_proxy.Tpo -c -o ios_webkit_debug_proxy-ios_webkit_debug_proxy.o `test -f 'ios_webkit_debug_proxy.c' || echo './'`ios_webkit_debug_proxy.c
ios_webkit_debug_proxy.c: In function ‘iwdp_get_content_type’:
ios_webkit_debug_proxy.c:1974:18: error: initialization discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
 1974 |     char *fext = strrchr(path, '.');
      |                  ^~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:677: ios_webkit_debug_proxy-ios_webkit_debug_proxy.o] Error 1
make[2]: Leaving directory '/home/michael-heuberger/code/binarykitchen/ios-webkit-debug-proxy/src'
make[1]: *** [Makefile:416: all-recursive] Error 1
make[1]: Leaving directory '/home/michael-heuberger/code/binarykitchen/ios-webkit-debug-proxy'
make: *** [Makefile:348: all] Error 2
```

**Comment by Ellivers** [comment]
You can get around this by adding `-Wno-error=discarded-qualifiers` in `src/Makefile`

```
CFLAGS = -g -O2 -Wall -Werror -Wno-error=discarded-qualifiers
```
(line 266)

**Comment by binarykitchen** [comment]
Thanks @Ellivers ...

... but no. Figured, on Arch Linux `yay -S ios-webkit-debug-proxy` does all that, and I'm good now 😎
