### ISSUE TITLE
Can't build on Ubuntu 13.04

### ISSUE THREAD

**Issue by dehuszar** [google/ios-webkit-debug-proxy#32]
I just attempted to build ios-webkit-debug-proxy on Ubuntu 13.04, but got the following errors when running 'make':

make  all-recursive
make[1]: Entering directory `/home/kaplan/repos/ios-webkit-debug-proxy'
Making all in src
make[2]: Entering directory`/home/kaplan/repos/ios-webkit-debug-proxy/src'
gcc -DHAVE_CONFIG_H -I. -I..  -I../include     -g -O2 -MT webinspector.o -MD -MP -MF .deps/webinspector.Tpo -c -o webinspector.o webinspector.c
webinspector.c: In function ‘wi_connect’:
webinspector.c:117:3: error: unknown type name ‘lockdownd_service_descriptor_t’
webinspector.c:117:44: warning: initialization makes integer from pointer without a cast [enabled by default]
webinspector.c:148:3: warning: passing argument 3 of ‘lockdownd_start_service’ from incompatible pointer type [enabled by default]
In file included from webinspector.c:22:0:
/usr/include/libimobiledevice/lockdown.h:82:19: note: expected ‘uint16_t _’ but argument is of type ‘int *’
webinspector.c:149:15: error: invalid type argument of ‘->’ (have ‘int’)
webinspector.c:155:37: error: invalid type argument of ‘->’ (have ‘int’)
make[2]: *_\* [webinspector.o] Error 1
make[2]: Leaving directory `/home/kaplan/repos/ios-webkit-debug-proxy/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/home/kaplan/repos/ios-webkit-debug-proxy'
make: **\* [all] Error 2

Any ideas what I can do to get around this?  I desperately need to debug some issues via Safari Mobile, don't have a Mac, and have had massive issues with Weinre staying failing.  Any help would be appreciated.

**Comment by artygus** [comment]
minimal libimobiledevice version required has been set to 1.2.0 with 8a90693a4fbd86f0c320c83954d6790b63381334
