### ISSUE TITLE
Can't make due gcc error

### ISSUE THREAD

**Issue by akhar** [google/ios-webkit-debug-proxy#340]
Ubuntu 19.20
I've run make and I've got
```
gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I../include/ios-webkit-debug-proxy   -I/usr/include/p11-kit-1    -g -O2 -Wall -Werror -MT ios_webkit_debug_proxy-webinspector.o -MD -MP -MF .deps/ios_webkit_debug_proxy-webinspector.Tpo -c -o ios_webkit_debug_proxy-webinspector.o `test -f 'webinspector.c' || echo './'`webinspector.c
webinspector.c:95:32: error: field ‘type’ has incomplete type
   95 |   enum idevice_connection_type type;
      |                                ^~~~
webinspector.c: In function ‘idevice_connection_get_ssl_session’:
webinspector.c:117:24: error: ‘CONNECTION_USBMUXD’ undeclared (first use in this function)
  117 |   if (!c || c->type != CONNECTION_USBMUXD || c->data <= 0) {
      |                        ^~~~~~~~~~~~~~~~~~
```

Lib versions:
```
autoconf — 2.69-11ubuntu1
automake — 1:1.16.1-4ubuntu3
libimobiledevice-dev — 1.2.1~git20181030.92c5462-1
libplist++-dev — 2.0.1~git20190104.3f96731-1
libplist-dev — 2.0.1~git20190104.3f96731-1
libtool — 2.4.6-11
libusb-1.0-0-dev — 2:1.0.23-1
libusb-dev — 2:0.1.12-32
usbmuxd — 1.1.1~git20181007.f838cf6-1
```

**Comment by artygus** [comment]
you need libimobiledevice master

**Comment by akhar** [comment]
I've try to make last libmobiledevice from Github, but can't due errors like `‘usbmuxd_device_info_t’ {aka ‘const struct <anonymous>’} has no member named ‘conn_type’`. How could I leave this vicious circle?

**Comment by artygus** [comment]
you could try building all of them, i.e. usbmuxd, libimobilidevice and libplist from master

**Comment by akhar** [comment]
Thanks!

**Comment by mpw-wwu** [comment]
v1.8.5 from

``` git checkout v1.8.5```

works with Ubuntu 18.04.3 without the need to recompile dependencies.

**Comment by Gizmo091** [comment]
> v1.8.5 from
> 
> ` git checkout v1.8.5`
> 
> works with Ubuntu 18.04.3 without the need to recompile dependencies.

This solution works for install, but could not connect to iOS 13 beta device

**Comment by mpw-wwu** [comment]
Sure, it just makes the probably outdated version install. It doesn't bring along the improvements that happend since then.

**Comment by erickhj** [comment]
> you could try building all of them, i.e. usbmuxd, libimobilidevice and libplist from master, make sure to remove all libmibolidevice-, usbmuxd-, libplist- packages

Can you explain what does this mean?. Do you mean cloning the rep from github then running make or something?

**Comment by BenjaminSchilller** [comment]
@artygus Thankx!

For all, who didn't understood the steps and marked artygus with a confused emoticon - the steps on i.e. Ubuntu 18.04:

1. remove package libplist with 
> sudo apt-get remove libplist-*

2. clone the package libplist with git
> git clone https://git.libimobiledevice.org/libplist.git

Do this with all the packages libplist, usbmuxd, libmibolidevice  as suggested.
For each package in order of the packages do:

> ./autogen.sh
> make
> sudo make install

**Comment by IbnAhmed** [comment]
> v1.8.5 from
> 
> ` git checkout v1.8.5`
> 
> works with Ubuntu 18.04.3 without the need to recompile dependencies.

it works. thanks.
