### ISSUE TITLE
Can't build on Ubuntu 14.04

### ISSUE THREAD

**Issue by digitalica** [google/ios-webkit-debug-proxy#58]
following the instructions on frontpage here, i got errors running make:

ios_webkit_debug_proxy.c:1724:15: error: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Werror=unused-result]
       asprintf(&s,
               ^
ios_webkit_debug_proxy.c:1743:13: error: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Werror=unused-result]
     asprintf(&header,
             ^
ios_webkit_debug_proxy.c:1749:13: error: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Werror=unused-result]
     asprintf(&footer, "</ol>%s</body></html>", (is_chrome_dev ?
             ^
cc1: all warnings being treated as errors
make[2]: **\* [ios_webkit_debug_proxy.o] Error 1
make[2]: Leaving directory `/home/robbert/git/ios-webkit-debug-proxy/src'
make[1]: **\* [all-recursive] Error 1
